name: potsoft
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # ======================================================

  get: ^4.6.5
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.8
  google_sign_in: ^5.4.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3
  intl: ^0.17.0

  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  url_launcher: ^6.1.7

  # file_picker: ^4.6.1
  # open_file: ^3.2.1
  # video_player: ^2.4.7
  # carousel_slider: ^4.1.1
  # uni_links: ^0.5.1
  # flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
# F9:3D:1E:00:4F:CB:5C:9C:FF:0A:09:16:0D:99:18:0D:71:5C:C6:F3
# DB:C2:E9:FE:52:A1:D0:1A:E0:1F:6E:2C:46:8F:FA:1D:1F:0A:7E:73:ED:44:94:A1:A4:5A:83:70:FB:9B:9A:D7
